### ISSUE TITLE
maybe a typo?

### ISSUE THREAD

**Issue by marabesi** [mathiasverraes/15yearsddd#5]
there is a phrase that I think is not complete.

File: https://github.com/mathiasverraes/15yearsddd/blob/master/manuscript/scott-millett/essay.md

Phrase: You should not have a them and us mentality

Probably there is something missing between "should have" and "them"?

**Comment by jcoplien** [comment]
It is valid English if you hyphenate “them-and-us”.

**Comment by mathiasverraes** [comment]
Thanks, I changed it to them-and-us
